// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AuthTabsController from "./auth_tabs_controller"
application.register("auth-tabs", AuthTabsController)

import MessagePopupController from "./message_popup_controller"
application.register("message-popup", MessagePopupController)

import PasswordToggleController from "./password_toggle_controller"
application.register("password-toggle", PasswordToggleController)

import PatientFormModalController from "./patient_form_modal_controller"
application.register("patient-form-modal", PatientFormModalController)

import SideBarButtonsController from "./side_bar_buttons_controller"
application.register("side-bar-buttons", SideBarButtonsController)
